
export const reviews = [
  {
    rating: 5,
    text: "Absolutely fantastic service! The plumber arrived on time and fixed the issue quickly. Highly recommended.",
    store: "Downtown Branch",
    customer: "Jane Doe",
    date: "2024-07-20",
    tags: ["Excellent Service", "Punctual", "Fast"],
    source: "GMB",
    status: "Replied",
    notes: "Followed up with a thank you note.",
    complaints: [],
    feedback: ["Great Service"],
    sentiment: "Positive",
  },
  {
    rating: 2,
    text: "The technician was late and didn't seem to know what he was doing. The problem is still not fixed.",
    store: "Westwood Store",
    customer: "John Smith",
    date: "2024-07-19",
    tags: ["Late Arrival", "Service Issue", "Late"],
    source: "Manual",
    status: "Not Replied",
    notes: "",
    complaints: ["Late Arrival", "Unresolved Issue"],
    feedback: [],
    sentiment: "Negative",
  },
  {
    rating: 4,
    text: "Good service overall, but a bit pricey compared to others.",
    store: "River North",
    customer: "Emily White",
    date: "2024-07-18",
    tags: ["Pricing", "Price"],
    source: "GMB",
    status: "Replied",
    notes: "",
    complaints: ["High Price"],
    feedback: ["Good Service"],
    sentiment: "Positive",
  },
  {
    rating: 1,
    text: "The store was not clean and the staff was rude. A very bad experience.",
    store: "South Beach",
    customer: "Michael Brown",
    date: "2024-07-17",
    tags: ["Cleanliness", "Rude Staff", "Rude"],
    source: "Internal",
    status: "Not Replied",
    notes: "Action assigned to store manager.",
    complaints: ["Cleanliness", "Rude Staff"],
    feedback: ["Bad Experience"],
    sentiment: "Negative",
  },
  {
    rating: 5,
    text: "Loved the new coffee blend! So fresh.",
    store: "Downtown Branch",
    customer: "Sarah Lee",
    date: "2024-07-21",
    tags: ["Product", "Fresh", "Recommended"],
    source: "GMB",
    status: "Replied",
    notes: "",
    complaints: [],
    feedback: ["Fresh", "Good taste"],
    sentiment: "Positive",
  },
  {
    rating: 3,
    text: "My bagel was stale. Disappointing.",
    store: "Westwood Store",
    customer: "Chris Green",
    date: "2024-07-20",
    tags: ["Product", "Stale"],
    source: "Manual",
    status: "Not Replied",
    notes: "",
    complaints: ["Stale"],
    feedback: ["Stale"],
    sentiment: "Neutral",
  },
];
